spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_test
spring.datasource.username=task_user
spring.datasource.password=5678
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true    